config/routes.rb
Rails.application.routes.draw do
  resources :todos do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :todo_items
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo

  def completed?
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo
  before_action :set_todo_item, except: [:create]
  def create
    @todo_item = @todo.todo_items.create(todo_item_params)

    redirect_to @todo
  end

  def destroy
    @todo_item = @todo.todo_items.find(params[:id])
    if @todo.destroy
      flash[:success] = "Todo List item was deleted."
    else
      flash[:error] = "Todo List item could not be deleted."
    end
    redirect_to @todo
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo, notice: "Todo item completed"
  end

  private

  def set_todo
    @todo = Todo.find(params[:todo_id])
  end

  def set_todo_item
    @todo_item = @todo.todo_items.find(params[:id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> -->
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo, @todo.todo_items.build])do |f| %>
  <%= f.text_field :content, placeholder: "Scribble down your To Do item here" %>
  <%= f.submit "Create it!" %>
<% end %>

app/views/todo_items/_todo_item.html.erb
  <div class="row clearfix">
  	<% if todo_item.completed? %>
  		<div class="complete">
  			<%= link_to complete_todo_todo_item_path(@todo, todo_item.id), method: :patch do %>
  				<i style="opacity: 0.4;" class="fa fa-check"></i>
  			<% end %>
  		</div>
  		<div class="todo_item">
  			<p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
  		</div>
  		<div class="trash">
  			<%= link_to todo_todo_item_path(@todo, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
  				<i class="fa fa-trash"></i>
  			<% end %>
  		</div>
  	<% else %>
  		<div class="complete">
  			<%= link_to complete_todo_todo_item_path(@todo, todo_item.id), method: :patch do %>
  				<i class="fa fa-check"></i>
  			<% end %>
  		</div>
  		<div class="todo_item">
  			<p><%= todo_item.content %></p>
  		</div>
  		<div class="trash">
  			<%= link_to todo_todo_item_path(@todo, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
  				<i class="fa fa-trash"></i>
  			<% end %>
  		</div>
  	<% end %>
  </div>

app/views/todos/_form.html.erb
<%= form_for(todo) do |f| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1 class="todo_list_title">Edit Todo List</h1>
<div class="forms">
  <%= render 'form', todo: @todo %>
</div>
<div class="links">
  <%= link_to 'Cancel', todos_path %>
</div>

app/views/todos/index.html.erb
<% @todos.each do |todo| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to todo.title, todo %>
    <p class="todo_list_sub_title"><%= todo.description %></p>
    </h2>
  </div>
<% end %>

<div class="links">
  <%= link_to "New Todo List", new_todo_path %>
</div>

app/views/todos/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>
<div class="forms">
  <%= render 'form', todo: @todo %>
</div>
<div class="links">
  <%= link_to 'Back', todos_path %>
</div>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_title"><%= @todo.title %></h2>
<p class="todo_list_sub_title"><%= @todo.description %></p>

<div id="todo_items_wrapper">
  <%= render @todo.todo_items %>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
</div>

<div class="links">
  <%= link_to 'Edit', edit_todo_path(@todo) %> |
  <%= link_to 'Delete', todo_path(@todo), method: :delete, data: { confirm: "Are you sure?" } %> |
  <%= link_to 'Back', todos_path %>
</div>